settings:
    stationname: Radio Bielefeld
    shortname: radiobielefeld
    description: 100% von hier. Der beste Mix
    baseurl: http://www.radiobielefeld.de
    playlist_url: http://www.radiobielefeld.de/nc/musik/playlist.html
    playlist_type: html

xpath:
    count_from: 2
    count_to: count(.//*[@id='c1190']/div/table/tr) + 2
    time: .//*[@id='c1190']/div/table/tr[%counter%]/td[1]/text()
    artist: .//*[@id='c1190']/div/table/tr[%counter%]/td[3]/text()
    title: .//*[@id='c1190']/div/table/tr[%counter%]/td[4]/text()
    duration: .//*[@id='c1190']/div/table/tr[%counter%]/td[2]/text()